# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Pagemerger
      run: |
        git clone https://github.com/tymbaca/pagemerger.git
        cd pagemerger 
        dotnet add package DocumentFormat.OpenXml --version 2.20.0
        dotnet add package CommandLineParser --version 2.9.1
        dotnet publish -o ./result -p:PublishSingleFile=true --self-contained false
        cd result
        sudo mv pagemerger /usr/local/bin
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
